package seaweedfs.core.document;

import io.netty.buffer.ByteBuf;

import java.time.Duration;

public interface Document<T> {
    /**
     * The unique filer ID of the {@link Document}, generated by master server.
     * consist of volume sequence nbr, comma delimiter, file id
     *
     * @return the document id.
     */
    String id();

    /**
     * The size in byte of the {@link Document}, sized by the master server.
     *
     * @return the document size
     */
    Long size();

    /**
     * The url of the {@Link Document}, generated by master server.
     * in the form of "http://host:port/id
     *
     * @return the document url.
     */
    String url();

    /**
     * The filer url of the {@Link Document}, generated by filer server.
     *
     * @return the document filer url.
     */
    String filerUrl();

    /**
     * The name of the {@Link Document}
     *
     * @return the document name.
     */
    String name();

    /**
     * The content of the {@link Document}.
     *
     * @return the content.
     */
    T content();

    /**
     * The optional expiration time for the {@link Document} (Duration.ZERO of {@link Duration} if not set).
     *
     * @return the expiration time.
     */
    Duration expiry();

    ByteBuf bytebuf();

    void from(ByteBuf byteBuf);
}
